# Generated by Django 5.2 on 2026-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_application_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Application deadline', null=True),
        ),
    ]
