# Generated by Django 6.0.2 on 2026-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL identifier for the article', unique=True)),
                ('author', models.CharField(default='Strategic Synergy Team', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='insights/images/')),
                ('category', models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('TALENT', 'Talent Acquisition'), ('CULTURE', 'Company Culture'), ('STRATEGY', 'Strategy'), ('TECH', 'HR Tech')], default='LEADERSHIP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
